server {
  listen 3000;

  root /usr/share/nginx/html/public;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /src/ {
    alias /usr/share/nginx/html/src/;
  }

  location = /manifest.json {
    add_header Content-Type application/manifest+json;
  }

  location = /src/serviceWorker.js {
    add_header Cache-Control "no-cache";
  }

  error_page 404 /offline.html;
}